%YAML 1.1
---
version: ">1.7.0 || @head"
export: |

    project "GoogleTest"

        kind "StaticLib"

        files "googletest/src/gtest-all.cc"
        includedirs "googletest/"

        zpm.export [[
            includedirs "googletest/include/"

            cppdialect "C++11"
            
            filter "system:macosx"
                defines "GTEST_USE_OWN_TR1_TUPLE=1"

            filter "system:windows"
                defines {
                  "GTEST_LANG_CXX11=1",
                  "GTEST_HAS_TR1_TUPLE=0"
                }

            filter "system:not macosx"
                defines "GTEST_USE_OWN_TR1_TUPLE=0"

            filter "system:posix"
                links "pthread"

            filter {}
        ]]

    project "GoogleMock"

        kind "StaticLib"

        files "googlemock/src/gmock-all.cc"
        includedirs "googlemock/"

        zpm.uses "GoogleTest"

        zpm.export [[
            includedirs "googlemock/include/"

            cppdialect "C++11"
        ]]
...
---
version: "<=1.7.0"
export: |

    project "GoogleTest"

        kind "StaticLib"

        files "src/gtest-all.cc"
        includedirs "./"

        zpm.export [[

            includedirs "include/"

            filter "system:macosx"
                defines "GTEST_USE_OWN_TR1_TUPLE=1"

            filter "system:not macosx"
                defines "GTEST_USE_OWN_TR1_TUPLE=0"

            filter "system:not windows"
                links "pthread"
        ]]