sudo: required
language: generic
matrix:
  include:
  - os: linux
    dist: trusty
    env: VERSION=6
  - os: linux
    dist: trusty
    env: VERSION=7
  - os: linux
    dist: trusty
    env: VERSION=5
  - os: osx
    osx_image: xcode8
    language: generic
install:
- source /dev/stdin <<< "$(curl -s https://raw.githubusercontent.com/Zefiros-Software/ZPM/features/refactor/script/install-zpm.sh)"
script:
- cd test && zpm run test-definition GoogleTest
notifications:
  slack:
    secure: qEI1ec8nzqjtH+/XAGWOumVaIBctmfncEYkNS2NqPvjLmzYlkwswavH/6xcLejWkLP7+Tq9Hffa+DUv4EVUBipAa/GYo5/hkRGOLtUZBvwpgUkyG+lP9cF2I+scaBcML/HgVynyzbQ3ilKrbBc+uuYghn2LdlHoIj7/hCTw9kt6KUkMLAF2fXn0e1PSl2NHSi6CO19e9VukozngAp5monwrgIQsPEWCR39ZiT4bHkcyTXfIvQ2WB0iETsE2qSqcArFK/HthE7GlzMkAs+URUObecpcx4V/pHSWf2QVe7R5YT7OucDmT8FaHYGIFr2Kt++wlDWFA86/A9Xy3Un+nWsoYmYg7PgjWMKgNXG0q24XbCAg2WlilkqB1/uiRhEdZO2pkbSgfKhhgwAA9O9AfMOZi6BjxjIzlLB0WdNZCHEILXa9xPcQpAjvhEOJO4IwbPfzqrUaprhn6I1/DvJb1JChUz79GUHtnO2/JUUFdGCKk6WbU3mQ+ssJaoGBklErTKVuP4Xt2Vi3lWyxZoxDDhOlfGnmhvIgTfM2qwyCxXi+291eE+T7mBSg3Cid4Iv0YDt+LWKajN0n+QCVO3slZC56DI04pUgeygcn8frC7VGO2fPXWSwgdCSmcQQs+X+jm37P3RtbZvRpnTj0yAoXH7mGoNF6yA1l8jaA0aip8gTow=
