sudo: required
language: generic
matrix:
  include:
  - os: linux
    dist: trusty
    env: VERSION=6
  - os: linux
    dist: trusty
    env: VERSION=7
  - os: osx
    osx_image: xcode9.2
    language: generic
global:
  env:
  - PROJECT=GoogleTest
  - PROJECT_TEMPLATE=default
install:
- source /dev/stdin <<< "$(curl -s https://raw.githubusercontent.com/Zefiros-Software/ZPM/dev/script/install-zpm.sh)"
script:
- cd test && zpm run test-definition GoogleTest
notifications:
  slack:
    secure: O21ngr2iB9NpY0YrkJSU2fBGLR9+Ws8oyRKMby9HN43zu1CvNXxNVaBttMbT/6ZBOjtYC83lQETavTRZh2xGw17FgXlzgenxaRVb/9fZPg+dbeLzrTMlmEZ8SMUuykleIbY48T2YhMsKQzi2z6JZbyONJvXU2BGvWIX8pNb7xO1bYsokkDScvt0hP21qx0DY7InYX4Bx7jMiauqrGQejF9k27FXZynwgMjy9ZTITkS6xuB05mm1i3LpzzEd3QSUqJVKNKuU6SfdSpSdT1gxI3PKMH1VreAsf3JZZXSaO/NLxbeWnBYbNWSY8D/6UiSnFwBMNT4b0FjvuOFeoN2BxiDrgDrUkvgDNk+Mj92VsbrHhL+0XV1JxSzm76ldqjPehfvIU6xCjt2pm5FA+ft0rBQ4wwvngw48mXwusC7fpTpwwDs+CUieN7n6b0GRQMEjxVTCkiEAeCLasBhVzXQ8GrUJ7w5RbcK9CmWIvG/GNyE0pLSzv2RDQMa2Ms7OJFE1JqoNMcNvSviim4h8vW0aewEBhHfnUtEJasxGDpMY8W7MZAw5KBMBFJd+FYsaC6xXrML84sWZhc7KQqo47wTLvfpMF6hGmScW5onUNJdbAK712K2vPCVnm9I0bt5S+a5m3Ze9oZN9vvqhKZKQVlHiWvwFUequqPZWIjwdOheV8Zwg=
